version: '3.1'
services:
  # database container - actency images
  db:
    # actency/docker-mysql available tags: latest, 5.7, 5.6, 5.5
    image: actency/docker-mysql:5.7
    container_name: redmine_db
    restart: always # unless-stopped
    ports:
      - "3306:3306"
    env_file:
      - ./env
  # redmine:latest
  redmine:
    image: redmine:latest
    container_name: redmine_web
    restart: always # unless-stopped
    ports:
      - "32768:3000"
    links:
      - db:mysql
    tty: true
    env_file:
      - ./env
    volumes:
      - ./restore:/usr/src/redmine/restore
      - ./files:/usr/src/redmine/files
      - ./themes:/usr/src/redmine/public/themes
  # phpmyadmin container - actency images
  phpmyadmin:
    image: actency/docker-phpmyadmin
    container_name: redmine_phpmyadmin
    restart: always # unless-stopped
    ports:
      - "8000:80"
    env_file:
      - ./env
    links:
      - db:mysql